hydragon:
# MoveIt-specific simulation settings
  moveit_sim_hw_interface:
    joint_model_group: controllers_initial_group_
    joint_model_group_pose: controllers_initial_pose_
# Settings for ros_control control loop
  generic_hw_control_loop:
    loop_hz: 300
    cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
  hardware_interface:
    joints:
      - lhip_y
      - lhip_p
      - lhip_r
      - lknee_p
      - lankle_r
      - lankle_p
      - rhip_y
      - rhip_p
      - rhip_r
      - rknee_p
      - rankle_r
      - rankle_p
      - waist_p
      - waist_r
      - lscaplae_y
      - lshoulder_p
      - lshoulder_r
      - lshoulder_y
      - lelbow_p
      - lwrist_y
      - lwrist_r
      - lwrist_p
      - neck_p
      - rscaplae_y
      - rshoulder_p
      - rshoulder_r
      - rshoulder_y
      - relbow_p
      - rwrist_y
      - rwrist_r
      - rwrist_p
    sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  controller_list:
    - name: RightArm_controller
      action_ns: follow_joint_trajectory
      default: True
      type: FollowJointTrajectory
      joints:
        - rscaplae_y
        - rshoulder_p
        - rshoulder_r
        - rshoulder_y
        - relbow_p
        - rwrist_y
        - rwrist_r
        - rwrist_p
    - name: LeftArm_controller
      action_ns: follow_joint_trajectory
      default: True
      type: FollowJointTrajectory
      joints:
        - lscaplae_y
        - lshoulder_p
        - lshoulder_r
        - lshoulder_y
        - lelbow_p
        - lwrist_y
        - lwrist_r
        - lwrist_p